spring:
  #激活哪一个环境的配置文件
  profiles:
    active: test
  application:
    name: data-redis-stream
  # redis配置
  redis:
    # 连接超时时间（毫秒）
    timeout: 1000ms
    lettuce:
      pool:
        # 连接池最大连接数
        max-active: 200
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池中的最小空闲连接
        min-idle: 1